# Generated by Django 3.2.4 on 2021-06-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210624_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('Draft', 'Draft')], default='active', max_length=20),
        ),
    ]
