# Generated by Django 3.2.4 on 2021-07-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_categories_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_tag_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_tag_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_tag_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
