# Generated by Django 3.2.4 on 2021-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pendding', 'Pendding'), ('not approved', 'Not approved')], default='pendding', max_length=30),
        ),
    ]
