# Generated by Django 3.2.4 on 2021-06-26 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Site Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(verbose_name='Site URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitesettings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SiteSetting',
                'verbose_name_plural': 'SiteSettings',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_posts_per_page', models.BigIntegerField(verbose_name='Number of posts per page')),
                ('posts_order', models.CharField(choices=[('new on top', 'NEW on top'), ('new at the bottom', 'NEW at the bottom')], max_length=50, verbose_name='Post order')),
                ('allow_comment_posting', models.BooleanField(default=False, verbose_name='Allow comments posting')),
                ('comment_approval', models.BooleanField(default=False, verbose_name='Comments Approval')),
                ('comment_order', models.CharField(choices=[('new on top', 'NEW on top'), ('new at the bottom', 'NEW at the bottom')], max_length=50, verbose_name='Comment order')),
                ('show_categories', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
    ]
