# Generated by Django 3.2.4 on 2021-06-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20210626_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='show_categories',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
