# Generated by Django 3.2.4 on 2021-06-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_option_show_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='allow_comment_posting',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Allow comments posting'),
        ),
        migrations.AlterField(
            model_name='option',
            name='comment_approval',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Comments Approval'),
        ),
    ]
